### ISSUE TITLE
Run will not start if starting on a world that isn't 1-1

### ISSUE THREAD

**Issue by cD1rtX3** [periwinkle9/smb-autosplitter#1] opened 2022-09-18 21:46 UTC
When attempting a run that doesn't start on 1-1, the timer doesn't start. If I press the button manually, the split will be doubled.

**Comment by periwinkle9** [comment] 2022-09-21 01:04
The autosplitter by design looks for the start of 1-1 to start the timer, so categories that start in a different level will have to have the timer started manually. I can look into the possibility of making the starting condition a bit more generic to allow for mid-game starts, though.
The double split sounds like it could be a bug, though. What category are you running that doesn't start in 1-1?

**Comment by cD1rtX3** [comment] 2022-10-09 15:28
I am attempting to run a glitched world as fast as possible, and when I
start the timer, it is usually around 1-3 frames before the 400. This
allows me to manually time the run more easily, however, it appears that
that also causes the timer to split twice. There is probably no way to fix
specifically that, however, allowing the timer to start on different world
would mean that I don't have to manually start the timer, and the double
split wouldn't happen.

**Comment by periwinkle9** [comment] 2022-10-21 00:31
I pushed a patch (54df14915cf0dda1b2cda31cc9696d4ec8e89c19) to start the timer from the first level after the title screen, whatever that level may be. If you're running a romhack that removes the title screen or modifies it in an incompatible way, it still might not start the timer, but at least it shouldn't double-split anymore.

Marking this as resolved, but feel free to re-open this or create a new issue if you run into any other problems.

**Closed as completed by periwinkle9** 2022-10-21 00:31 UTC
